version: 2.1

orbs:
  ipsec: danackerson/ipsec@0.2.2

commands:
  prepare_deploy_script:
    steps:
      - checkout
      - run:
          name: Prepare deploy script for Traefik Proxy server
          command: |
            cat \<<EOF >deploy_script.sh
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "\
            mkdir traefik || true && \
            touch traefik/acme.json && \
            chmod 600 traefik/acme.json"

            scp traefik.toml $SSH_USER@$SSH_HOST:~/traefik/traefik.toml

            ssh $SSH_USER@$SSH_HOST "\
            docker network create web || true && \
            docker rm -f traefik || true && \
            docker run -d --restart=always --network='web' \
              --label='traefik.frontend.rule=Host:monitor.ackerson.de' \
              -e DO_AUTH_TOKEN=$CTX_DIGITALOCEAN_TOKEN \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v ~/traefik/traefik.toml:/traefik.toml \
              -v ~/traefik/logs:/var/log/traefik/ \
              -v ~/traefik/acme.json:/acme.json \
              -p 80:80 -p 443:443 \
              --name traefik arm32v6/traefik:1.7"
            EOF

            chmod u+x deploy_script.sh

            # NOTE: these are now circleCI 2.1 "Pipeline" builds which run as Workflows
            # and therefore have the org-global context env vars. they do NOT yet
            # support passing build-parameters e.g. --data build_parameters[DEPLOY_SERVER_IP]=$NEW_SERVER_IPV4
            # https://circleci.com/docs/api/#trigger-a-new-build-by-project-preview
            #curl -X POST \
            #  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/ackerson.de-go/build?circle-token=${CTX_CIRCLECI_API_TOKEN}

workflows:
  deploy-propagate:
    jobs:
      - ipsec/remote-deploy:
          context: org-global
          name: deploy-trafik
          pre-steps:
            - prepare_deploy_script

